# Generated by Django 2.1.7 on 2019-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
