# Generated by Django 2.2b1 on 2019-03-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_quizquestion_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='module',
        ),
        migrations.RemoveField(
            model_name='component',
            name='question_text',
        ),
    ]
