# Generated by Django 2.1.7 on 2019-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_quizquestion_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
