# Generated by Django 2.1.7 on 2019-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
