# Generated by Django 2.1.7 on 2019-03-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190325_0925'),
        ('courses', '0003_auto_20190324_2255'),
    ]

    operations = [
    ]
