# Generated by Django 2.1.7 on 2019-03-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_quizresult'),
        ('courses', '0005_merge_20190325_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_progress', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Learner')),
            ],
        ),
    ]
