# Generated by Django 2.1.7 on 2019-04-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='test_user',
            new_name='instructor_user',
        ),
    ]
