# Generated by Django 2.1.7 on 2019-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CECU',
            field=models.IntegerField(default=1),
        ),
    ]
