# Generated by Django 2.1.7 on 2019-04-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190405_1223'),
        ('courses', '0008_course_cecu'),
    ]

    operations = [
    ]
