# Generated by Django 2.1.7 on 2019-04-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190410_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='Module',
        ),
        migrations.AddField(
            model_name='component',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='component',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Module'),
        ),
    ]
