# Generated by Django 2.1.7 on 2019-04-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190411_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='course',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='module',
            new_name='Module',
        ),
    ]
