# Generated by Django 2.1.7 on 2019-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190411_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='component',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
