# Generated by Django 2.1.7 on 2019-04-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190417_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
    ]
