# Generated by Django 2.1.7 on 2019-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20190423_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
