# Generated by Django 2.1.7 on 2019-04-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20190423_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
