# Generated by Django 2.1.7 on 2019-04-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_module_question_number'),
        ('courses', '0022_auto_20190426_0136'),
    ]

    operations = [
    ]
