# Generated by Django 2.1.7 on 2019-04-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_merge_20190426_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
