# Generated by Django 2.2b1 on 2019-04-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_quizresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
