# Generated by Django 2.2b1 on 2019-04-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_delete_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='CECU',
            field=models.IntegerField(default=0),
        ),
    ]
